import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { 
  Brain, 
  Globe, 
  ShoppingCart, 
  TrendingUp, 
  Users, 
  Wifi,
  ChefHat,
  Smartphone,
  Heart
} from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Meal Plans',
    description: 'Get personalized nutrition plans generated by advanced AI, tailored to your goals and Nigerian food preferences.',
    badge: 'Core',
    color: 'primary'
  },
  {
    icon: Globe,
    title: 'Nigerian Recipe Integration',
    description: 'Authentic local dishes like jollof rice, egusi, and pounded yam integrated with modern nutrition science.',
    badge: 'Cultural',
    color: 'accent'
  },
  {
    icon: ShoppingCart,
    title: 'Smart Grocery Lists',
    description: 'Auto-generated shopping lists optimized for Nigerian markets and local ingredient availability.',
    badge: 'Pro',
    color: 'secondary'
  },
  {
    icon: TrendingUp,
    title: 'Progress Analytics',
    description: 'Track your nutrition intake, goals progress, and health metrics with detailed insights and trends.',
    badge: 'Pro',
    color: 'primary'
  },
  {
    icon: Smartphone,
    title: 'Voice-Activated AI',
    description: 'Ask for meal suggestions, nutrition info, or recipe modifications using natural voice commands.',
    badge: 'Pro',
    color: 'accent'
  },
  {
    icon: Wifi,
    title: 'Offline Mode',
    description: 'Access your meal plans and recipes even without internet - perfect for areas with unreliable connectivity.',
    badge: 'Pro',
    color: 'secondary'
  },
  {
    icon: Users,
    title: 'Community Forum',
    description: 'Connect with other health enthusiasts, share recipes, and get motivation from the NutriVibe community.',
    badge: 'Pro',
    color: 'primary'
  },
  {
    icon: Heart,
    title: 'Health Goal Tracking',
    description: 'Whether it\'s weight loss, muscle gain, or maintaining health - track your journey with precision.',
    badge: 'Core',
    color: 'accent'
  },
  {
    icon: ChefHat,
    title: 'Recipe Customization',
    description: 'Modify recipes based on allergies, preferences, or available ingredients with AI-powered suggestions.',
    badge: 'Core',
    color: 'secondary'
  }
];

const getBadgeColor = (color: string) => {
  switch (color) {
    case 'primary':
      return 'bg-primary/10 text-primary border-primary/20';
    case 'secondary':
      return 'bg-secondary/10 text-secondary border-secondary/20';
    case 'accent':
      return 'bg-accent/10 text-accent border-accent/20';
    default:
      return 'bg-muted text-muted-foreground';
  }
};

const FeaturesSection = () => {
  return (
    <section id="features" className="py-20 lg:py-32 bg-background">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <Badge variant="outline" className="mb-4">
            Powerful Features
          </Badge>
          <h2 className="text-3xl md:text-5xl font-bold mb-6">
            Everything You Need for{' '}
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              Healthy Living
            </span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            From AI-powered meal planning to Nigerian cultural integration - 
            discover features designed to transform your nutrition journey.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <Card 
              key={index} 
              className="group hover:shadow-elegant transition-all duration-300 hover:-translate-y-2 border-border/50 hover:border-primary/20"
            >
              <CardHeader className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className={`p-3 rounded-lg bg-gradient-to-br ${
                    feature.color === 'primary' ? 'from-primary/10 to-primary-glow/10' :
                    feature.color === 'secondary' ? 'from-secondary/10 to-secondary/20' :
                    'from-accent/10 to-accent/20'
                  }`}>
                    <feature.icon className={`h-6 w-6 ${
                      feature.color === 'primary' ? 'text-primary' :
                      feature.color === 'secondary' ? 'text-secondary' :
                      'text-accent'
                    }`} />
                  </div>
                  <Badge variant="outline" className={getBadgeColor(feature.color)}>
                    {feature.badge}
                  </Badge>
                </div>
                <CardTitle className="text-xl group-hover:text-primary transition-smooth">
                  {feature.title}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription className="text-base leading-relaxed">
                  {feature.description}
                </CardDescription>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Call to Action */}
        <div className="text-center mt-16">
          <div className="bg-gradient-subtle rounded-2xl p-8 md:p-12 shadow-warm">
            <h3 className="text-2xl md:text-3xl font-bold mb-4">
              Ready to Transform Your{' '}
              <span className="bg-gradient-warm bg-clip-text text-transparent">
                Nutrition Journey?
              </span>
            </h3>
            <p className="text-lg text-muted-foreground mb-6 max-w-2xl mx-auto">
              Join thousands of Nigerians who have already started their healthier lifestyle with NutriVibe.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;