// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkwuifmmnrvzyxduzxkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrd3VpZm1tbnJ2enl4ZHV6eGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTM5MzYsImV4cCI6MjA3MTEyOTkzNn0.GsYKolLGAs2J77voHHcM4EgCdfqwb64uZRihUDhZ_Kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Prevent multiple auth state changes
  },
  global: {
    headers: { 'x-my-custom-header': 'nutri-vibe-naija' },
  },
  // Add connection limits to prevent resource exhaustion
  realtime: {
    params: {
      eventsPerSecond: 2 // Limit realtime events
    }
  }
});